version: '3.9'

services:
  db:
    restart: always
    env_file:
      - .env.prod
    # No ports exposed to the host
    
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn mini_project.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    env_file:
      - .env.prod
    expose:
      - 8000
    
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web 