version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume: