version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: assetdb
      POSTGRES_USER: assetuser
      POSTGRES_PASSWORD: assetpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    command: gunicorn mini_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: