# Generated by Django 5.1.7 on 2025-03-29 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('work_email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(choices=[('TL', 'Timor Leste'), ('PNG', 'Papua New Guinea'), ('AUS', 'Australia'), ('FJI', 'Fiji'), ('IDN', 'Indonesia'), ('OTH', 'Other')], help_text='Select the country where employee is based', max_length=3)),
                ('other_country', models.CharField(blank=True, help_text="Specify country if 'Other' is selected", max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('MOBILE', 'Mobile Phone'), ('OTHER', 'Other')], max_length=10)),
                ('other_asset_type', models.CharField(blank=True, help_text="Specify asset type if 'Other' is selected", max_length=50, null=True)),
                ('asset_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('is_working', models.BooleanField(default=True, help_text='Is the device in good working condition?')),
                ('has_adapters', models.BooleanField(default=False, help_text='Do you have any adapters (HDMI, USB-C, etc)?')),
                ('adapter_details', models.TextField(blank=True, help_text='Specify which adapters you have', null=True)),
                ('charger_replaced', models.BooleanField(default=False, help_text='Have you ever had your laptop charger replaced?')),
                ('number_of_chargers', models.PositiveSmallIntegerField(default=1, help_text='How many chargers do you keep?')),
                ('charger_locations', models.CharField(blank=True, help_text='Where do you keep your chargers? (e.g., home/office)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_assets', to='asset_app.employee')),
            ],
        ),
    ]
