# Generated by Django 5.1.7 on 2025-04-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='condition_details',
            field=models.TextField(blank=True, help_text="Additional details about the asset's condition (required if status is 'Not in Good Condition')", null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Good Condition'), ('MAINTENANCE', 'Under Maintenance'), ('POOR', 'Not in Good Condition')], default='GOOD', help_text='Current status of the asset', max_length=20),
        ),
    ]
